version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TuPasswordSegura123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - reserva-net

  backend:
    build:
      context: ./reserva-espacios-back
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      - sqlserver
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ReservasDB;User Id=sa;Password=TuPasswordSegura123;
    ports:
      - "5000:80"
    networks:
      - reserva-net

  frontend:
    build:
      context: ./reserva-espacios-front
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - reserva-net

volumes:
  sql_data:

networks:
  reserva-net:
    driver: bridge
